#!/usr/bin/env python

import sys

from groq import Groq

model = "mixtral-8x7b-32768"

reminder = """
Reminder:
- do not include tickmarks to separate the code
- include only the code, code comments and docstring
- optimize and simplify the code
- change variable names and function name to make the code more readable
- write type annotations
- do not include anything else besides the code
"""

system_prompt = """
You are a helpful coding assistant. You will be provided with a python
function. Your task is to write the function with the same functionality,
but with an included detailed docstring.
Style of docstring:
---
Short description.

Long description.

Args:
    arg: type
        description
    arg: type
        description

Returns:
    type: description

Examples:
>>> example
>>> example
---
""" + reminder
user_prompt = """
Code:
```
{code}
```
"""


def output(inp):
    client = Groq()

    out = client.chat.completions.create(
        messages=[
            {"role": "assistant", "content": system_prompt},
            {"role": "user", "content": user_prompt.format(code=inp)},
        ],
        model=model,
    )

    out = out.choices[0].message.content

    return out


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit()
    code_input = "\n".join(sys.argv[1:])
    # code_input = """
    # def sum_two_numbers(a, z):
    #     xx = a + z + z
    #     yy = a - z
    #     return yy + 1 - 1
    # """
    code_output = output(code_input)
    for line in code_output.split("\n"):
        if "```" in line:
            continue
        print(line)
